name: Provision Github Cloud Desktop
on: [workflow_dispatch]
jobs:
  github-computer:
    runs-on: ubuntu-latest
    container: ghcr.io/sabrehagen/desktop-environment:latest
    steps:
      - name: Start Desktop Environment Remote Access
        run: |
          whoami
          ls -l .
          pwd
          tmux start-server
          /home/loftwah/.config/scripts/startup.sh
          /home/loftwah/.yarn/bin/lt --port 8080
